### ISSUE TITLE
(Godot 3.4) Unable to install plugin properly

### ISSUE THREAD

**Issue by Thane5** [doradoro/Godot-Lazy-Import#2]
After enabling this addon, i get this error:

```
Lazy Import : The plugin is running!
 modules/gdscript/gdscript_functions.cpp:774 - Lazy Import ERROR : 0 should be >= 0
 modules/gdscript/gdscript_functions.cpp:774 - Lazy Import ERROR : Wrong configuration

```

**Comment by padreputativo** [comment]
Bug solved! try to download the last version on here as a zip and overwrite the addons directory only...

It will take a few days to be approved in the Asset Library!
